### PR TITLE
Parse Readme

### PR DESCRIPTION
**Pull request by simonv3**
# What's New
* A rakefile that processes the existing conferences.yml (or creates one if it doesn't exist) and appends whatever is new in the readme.md, or updates things in conferences.yml if the readme has changed it. 

This can cause a problem with duplicate content though, and when which gets updated. For website and twitter, the readme should probably always have the most up to date content, unless you want to do it the other way around where the readme is generated from the data in the conferences.yml file.

Thoughts @RichardLitt @Stephn-R?

### CODE REVIEW

**Comment by RichardLitt** [comment]
So, if this works like that, awesome. Question: Do you have a proposed framework for showing the conferences.yml file nicely in a website? Otherwise, isn't this just an alternative datastore that clutters up the repo?

**Comment by simonv3** [comment]
Yaml gets processed by jekyll into an easy to use list I'm fairly sure. Have a look here: https://github.com/doubleunion/opendiversitydata

That way you're not relying on javascript, and your site will be much more accessible. 

Converting it to JSON instead is trivial if you don't wan to go down that route.

**Comment by Stephn-R** [comment]
There are converters to do that already. It would not be a concern to fight
between JSON or YAML

**Comment by RichardLitt** [comment]
Alright, cool. Let's merge it.

**Comment by Stephn-R** [comment]
@simonv3 @RichardLitt So is this new Rakefile for generating the README.md?

**Comment by simonv3** [comment]
The other way around. Running it should update the conferences.yml with
whatever is in the readme.

**Comment by simonv3** [comment]
But like I said, it probably makes more sense to do it the other way.

**Comment by Stephn-R** [comment]
Why not do both? Just change the order with some param

**Comment by simonv3** [comment]
I'm not sure whether it makes sense to do both. We'll have to decide where the canonical source of the information is, otherwise we'll get conflicts left and right. Is it conferences.yml or readme? Like I said, I think making it conferences.yml makes the most sense from a holistic data point of view, but that might be harder to get people to do a simple PR to (even though it's about the same level of complexity, conferences.yml is much more hidden than readme.md, it's a mental step - one's a plain text file, the other is actually data, which might intimidate casual contributors). 

Also before this PR there was no other source than the readme, so creating that functionality was probably excessive if @RichardLitt didn't really like the direction that was going in. I wasn't even sure whether yml is what made the most sense (vs json, etc).

**Comment by RichardLitt** [comment]
I also don't think we should do both. I think there should be one source file for users to edit. 

So... now to use this .yml file somehow. :D

**Pull request merged**
