### PR TITLE
adds active indgredients

### PR DESCRIPTION
**Pull request by bdougie**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Looks cool to me. Can you alphabetize it properly?

**Comment by bdougie** [comment]
Oh sorry, didn't even notice there was an order

**Comment by RichardLitt** [comment]
No worries!

I'm going to be overhauling this at some point to include reasons why these conferences are _awesome_. Can you sum up your reason for adding it here?

**Comment by bdougie** [comment]
Active Ingredients is a conference produced by Designers + Geeks. Over the course of the day, we'll look at the emerging JAMstack technologies (Javascript, APIs, Markup) being used to create some of the finest sites on the web.

**Comment by RichardLitt** [comment]
Thanks!

**Pull request merged**
