### PR TITLE
add jax london to european section

### PR DESCRIPTION
**Pull request by cbrueckner**
#### Conference Name

> This conference is / looks awesome because... . - [@yourName](https://github.com/yourname]

* **Website:**
* **Location:**
* **Date:**
* **Registration:** _Delete if past._
* **Call for Presenters:** _Delete if past._
* **Has reminder mailing list:**
* **Twitter:** [@conf](https://twitter.com/conf)
* **Twitter Hashtag:** _What did or will people use to talk about the conf? Delete if unknown or not set yet._
* **Tags:**
* **Videos:** _Post the location if there is one. Delete if not known._
* **Notes or roundups:** _Post the location if there is one. Delete it not done yet._
* **Attendees:** _Add your name if you've attended._

### CODE REVIEW

**Comment by TejasQ** [comment]
?

**Comment by cbrueckner** [comment]
Hey, sorry i only wanted to add the link for jax london under the european section. did i something wrong?

**Comment by TejasQ** [comment]
Your entire issue is just a template...

**Comment by RichardLitt** [comment]
Thanks @cbrueckner

**Pull request merged**
